# timm model name
vit_type: vit_base_patch14_dinov2.lvd142m
# vit stride size:
#     You can use 7 or 14 for models with a patch size of 14 ,
#     and 8 or 16 for models with a patch size of 16
stride: 14

data:
  image_list: data/voc_train.txt # path to the training image list
  data_list: null
  is_raw_feat_cached: True
  input_size: [518, 518]
  num_max_samples: 0
model:
  vit:
    type: ${vit_type}
    stride: ${stride}
  denoiser:
    enable_pe: True
    denoiser_type: "transformer"
optim:
  seed: 18
  lr: 0.02
  weight_decay: 1e-5
  batch_size: 64
  num_workers: 8
  num_iters: 40000
  base_lr: 2.0e-04 # learning rate for a batch size of 256
  min_lr: 1.0e-06
  adamw_beta1: 0.9
  adamw_beta2: 0.999
logging:
  print_freq: 50
  vis_freq: 1000
  num_vis_samples: 5
  save_freq: 5000
load_from: null
