data:
  image_list: data/voc_train.txt # path to the training image list
  input_size: [518, 518] # input image size
  num_patches: 768 # number of transformed views per image
  # each time, we denoise num_imgs images starting from start_idx in the image list
  start_idx: 0 # start index of the image list
  num_imgs: 1 # number of images to denoise in a single run
  overwrite: False # whether to overwrite the existing denoised features
model:
  denoiser: # stage-1 denoiser settings
    enable_residual_predictor: True # whether to use the residual predictor
    noise_map_height: null # will be auto-computed based on the model's stride and patch size
    noise_map_width: null # will be auto-computed based on the model's stride and patch size
  neural_field: # semantics neural field F, using instantNGP
    base_resolution: 16
    max_resolution: 1024
    n_levels: 16
    n_features_per_level: 8
    log2_hashmap_size: 20
  vit:
    type: vit_base_patch14_dinov2.lvd142m # timm model name
    stride: 14 # vit stride size, 14 or 16 depending on the model's patch size
optim:
  seed: 18
  lr: 0.01
  freeze_shared_artifacts_after: 0.5 # int(0.5 * num_iters)
  num_iters: 20000
  weight_decay: 1e-5
  num_workers: 8
logging:
  print_freq: 1000
  num_vis_samples: 5
